### ISSUE TITLE
Module Name structure

### ISSUE THREAD

**Issue by dieskim** [euforic/Titanium-Count.ly#8]
Hi,

It would be great to have both the Android and iOS module naming structure match - as one would then be able to only include the module in your code once.
Currently the iOS and Android module are not the same and thus we currently have to require the modules as follow:

**In tiapp.xml**
```
<module platform="android">ly.count</module>
<module platform="iphone">count.ly</module>
```
**In app code - alloy.js**
```
if (Ti.Platform.name == 'iPhone OS'){
    var Countly = require('count.ly');
    Countly.start('API_KEY','http://cloud.count.ly');
}else{
    var Countly = require('ly.count');
    Countly.countInit('http://cloud.count.ly','API_KEY');
};

```

Ideally we would want them to be the same so that we could just require once

```
 var Countly = require('ly.count');
```

Would you be able to change the iOS module to match the Android (I personally think the Android naming convention is the correct one?) or would it be easier to change the Android to match the iOS module?

**Comment by euforic** [comment]
Closing for now since I'm not sure I want to make this change. Let me see if there is a way i can fix for android so it shows like ios to be consistent.
