### ISSUE TITLE
Titanium 3.5.0 GA - Architecture: x86_64

### ISSUE THREAD

**Issue by thiagodelmotte** [euforic/Titanium-Count.ly#9]
Hello Guys,

Titanium 3.5.0 GA needs architecture 64 bits for every module now. Do you have any plan for update count.ly modules?

When I build the project I get this message:
[ERROR] Script Error Couldn't find module: count.ly for architecture: x86_64

Without it we can't continue use this sdk.

Thank you!

**Comment by dieskim** [comment]
Hey - I added 64Bit support - https://github.com/dieskim/Titanium-Count.ly

**Comment by thiagodelmotte** [comment]
Perfectly @dieskim ! Thank you! It's working!
